# Generated by Django 4.1.1 on 2022-10-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_comment_auctionlisting_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(related_name='watchlists', to='auctions.auctionlisting'),
        ),
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
